# Generated by Django 3.1.3 on 2021-04-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210407_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
